#!/usr/bin/python
##############################
#
# File: lcovPlus.py
# Author: Teng Long (tlong@cs.umd.edu)
# Version: 0.1.1
# Descrpition:
#   This is a tool that provides enhanced features processing tracefiles(.info)
#   generated by lcov.
# Created: Jul. 25th, 2011
# Updated:
#   Jul 26, 2011: Changed the option processing with "getopt" module of python
# Bus:
#   1. if use with '| less' in Unix/Linux, a "Broken pipe" excpetion
#      will be raised.
#   2. when (-r rl r2), r1 and r2 should be anble to be quoted by ""
##############################


import os
import sys
import getopt

version = 0.1

debugFlag = False

def printerr(content):
    if type(content) != type("string"):
        content = str(content)
    if debugFlag == True:
        sys.stderr.write(content + '\n')
        
def errorInfo():
    print >> sys.stderr, "Use lcovPlus --help to get more information"
    sys.exit(1)

def help():
    print '''Usage: lcovPlus [OPTIONS]

Use lcovPlus to process tracefile generated by lcov.

Misc:
  -h, --help                    Print this help, then exit
  -v, --version                 Print version Number, then exit

Operation:
  -r, --replace                 Replace the prefix of source files
  -a, --add-tracefile FILE      Add contents of tracefile

Options:
  -o, --output-file FILENAME    Write data to FILENAME instead of stdout
  -d, --debug-mode              Output debug information for lcovPlus

To report a bug, please contact tlong@cs.umd.edu
'''    


## Get arguments
args = sys.argv[1:]
optlist, args = getopt.gnu_getopt(args, "hvrda:o:", ['help', 'version', 'replace', 'add-tracefile', 'output-file', 'debug-mode']) # option list


##############################
# option & argument processing
##############################

aFlag = False
rFlag = False
oFlag = False

## singple options

opts = [opt[0] for opt in optlist]

if '--help' in opts or '-h' in opts:
    help()
    sys.exit(0)

elif '--version' in opts or '-v' in opts:
    print version
    sys.exit(0)

elif '-d' in opts or '--debug-mode' in opts:
    debugFlag = True


infileList = [] # the list of inputed files.
replacePair = None # the list of prefix replacement pairs
outputFile = None

for item in optlist:
    if item[0] == '-a' or item[0] == '--add-tracefile':
        aFlag = True
        infileList.append(item[1])

    elif item[0] == '-r' or item[0] == '--replace':
        rFlag = True
        if len(args) == 2:
            replacePair = (args[0], args[1])
        else:
            errorInfo()
    elif item[0] == '-o' or item[0] == '--output-file':
        oFlag = True
        outputFile = item[1]
    else:
        errorInfo()
        
printerr("infileList: " + str(infileList))
printerr("replacePair: " + str(replacePair))



##############################
# dealing with '-r': replacement
##############################
if rFlag == True:
    if len(infileList) == 0:
        print >> sys.stderr, "lcovPlus: Please add exactly ONE tracefile by '-a' for replacement"
        errorInfo()
    elif len(infileList) >= 2:
        print >> sys.stderr, "lcovPlus: Please only add ONE tracefile for replacement"
        errorInfo()
    else:
        if oFlag == True: # output file specified
            outstream = open(outputFile, 'w')
        else:
            outstream = sys.stdout
            
        infile = open(infileList[0], 'r')
        for item in infile.readlines():
            if not item.startswith("SF:"):
                try:
                    outstream.write(item)
                except:
                    None
            else: # the 'SF:' lines
                rawline = item[3:]
                replaceFlag = False # whether replaced anything
                # compare every replacement pair
                if rawline.startswith(replacePair[0]):
                    newline = 'SF:' + replacePair[1] + rawline[len(replacePair[0]):]
                    replaceFlag = True
                if replaceFlag == False:
                    outstream.write(item)
                else:
                    outstream.write(newline)
                    

        # Close files
        infile.close()
        if oFlag == True:
            outstream.close()
                
                
        
